language: r
cache: packages
sudo: false

r_packages:
  - covr

addons:
  postgresql: "10"
  apt:
    packages:
      - libpq-dev

services:
  - postgresql

after_success:
  - Rscript -e 'covr::codecov()'
